# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCCHelperDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CCCHelperDemo
  pod 'CCCHelper', :path => '../CCCHelper'

end
